### ISSUE TITLE
evaluator Add Subtract Formula has 4 arguments

### ISSUE THREAD

**Issue by hellowac** [dbrnz/pptx2svg#6]
when I render preset shape circularArrow to svg, raise exception :

+- xH 0 dxB 0  Evaluator.<lambda>() takes 4 positional arguments but 5 were given

in formula.py and ecma-376 document(20.1.9.11 gd (Shape Guide))， Add Subtract Formula have 3 arguments, include Evaluator instance self, there should have 4 arguments, bug there have 5 arguments!

I read a lot of documents and search by google, but no solution has been found.

I check presetShapeDefinitions.xml file,  I found circularArrow definition has some tag:

```xml
<gd name="xB" fmla="+- xH 0 dxB 0"/>
<gd name="yB" fmla="+- yH 0 dyB 0"/>
```

so this is a bug or error ?

**Comment by dbrnz** [comment]
Hmm, it looks like something's not right in `presetShapeDefinitions.xml`. That was grabbed from [here](https://github.com/scanny/python-pptx/blob/master/spec/ISO-IEC-29500-1/schemas/dml-geometries/OfficeOpenXML-DrawingMLGeometries/presetShapeDefinitions.xml) and came from ISO-IEC-29500-1, with the original [here](https://standards.iso.org/ittf/PubliclyAvailableStandards/c071692_ISO_IEC_29500-4_2016_Electronic_inserts.zip) -- they all contain the same (erroneous) definitions.

I wonder if the definitions for `xB` and `yB` should read:
```
<gd name="xB" fmla="+- xH 0 dxB"/>
<gd name="yB" fmla="+- yH 0 dyB"/>
```

Does this do the right thing for you?

I see that definitions for the other types of circular arrows (left, right, etc) contain the same error.

**Comment by hellowac** [comment]
Actually not, It seems like we're caught in a loop.

I read some people asked MS question, it fixed some preset shape definition error, but not include this.

question url: [https://learn.microsoft.com/en-us/answers/...](https://learn.microsoft.com/en-us/answers/questions/928553/actual-rendering-of-wedgerectcallout-is-different)  

fixed file download url: [https://mailman.vse.cz/pipermail/sc34wg4/2018-November/004555.html](https://mailman.vse.cz/pipermail/sc34wg4/2018-November/004555.html)

and I not found some &lt;*OpenXML Implementation Guide*&gt; file.

**Comment by dbrnz** [comment]
Thanks for your research -- all should now be well.
